name = "alicesaidhi/conch_analysis"
version = "0.2.2-rc.2"
private = false
includes = ["src/**", "pesde.toml"]

[target]
environment = "roblox"
lib = "src/lib.luau"
build_files = ["src"]

[dependencies.types]
name = "alicesaidhi/conch_types"
version = "^0.2.1"
index = "https://github.com/daimond113/pesde-index"
target = "roblox"
